let constant = {
    TRUESTATUS: 1,
    FALSESTATUS: 0,
    MISSINGPARAMS: 'Please provide at least one param',
    TRUE: true,
    FALSE: false,
    TRUEMSG: 'Successful',
    FALSEMSG: 'Please try again later',
    SENTMSG: 'Sent successfully',
    INVALIDPARAMS: 'Invalid parameters',
    CODEUSED: 'Code already used',
    VERIFYMAIL: 'Verification Link has been sent on your mail',
    NOTREGISTERED: 'This email not registered with any account',
    WRONGCODEUSED: 'Verification code is not correct.',
    EXISTSMSG: 'associated with another account(Account already taken, try another)',
    VERIFYPENDING: 'Your account verification pending.',
    VERIFYDENY: 'Your document verification declined',
    DISABLEACCOUNT: 'Your account is disable by admin',
    SOMETHINGWRONG: 'Something went wrong. Please try again later',
    NOTAUTHERIZED: 'You can not verify driver account',
    USERIMAGE: 'static/users/',
    DRIVERIMAGE: 'static/drivers/',
    DOCIMAGE: 'static/driverDocs/',
    VEHICLEIMAGE: 'static/vehicles/',
    VEHICLETYPEIMAGE: 'static/vehicleTypes/',
    CUSTOMERIMAGE: 'static/customers/',
    PROMOTIONIMAGE: 'static/promos/',
    PATHIMAGE: 'static/paths/',
    TRIPCATIMAGE: 'static/tripcategories/',
    ADDMSG: 'Added successfully',
    UPDATEMSG: 'Updated sucessfully',
    SAVEMSG: 'Saved sucessfully',
    DELETEMSG: 'Deleted sucessfully',
    NOFILEMSG: 'No file selected',
    SCHEDULEMSG: 'Booking schedule successfully',
    CARDALREADYADDED: 'Card already added',
    NOTAXINEARBY: 'No taxi available nearby, Please try after some time',
    LATEMSG: 'Oops you are late this time..',
    CANCELREQUESTMSG: 'Request Cancel by User',
    LIMIT: 30,
    INVALIDCODE: 'You have entered invalid code',
    DISABLECODE: 'Discount not available on this code',
    EXPIREDCODE: 'Promocode expired',
    ALREADYUSEDCODE: 'Promocode already Used',
    REACHEDCODELIMIT: 'You have reached usage limit,You can not used this code.',
    NOTSAMEPASSWORDS: "Passwords don't match",
    WRONGCREDENTIALS: 'Wrong credentials',
    NOPASSWORDPROVIDED: 'Please Provide Password',
    // Aman
    ERRORLOGINMESSAGE: 'Email or password is incorrect.',
    ERR: 'Something went wrong please try again later.',
    PRODUCTDELETE: 'Product is deleted successfully.',
    PRODUCTSUCCESS: 'Product is  added successfully.',
    STOREUPDATE: 'Store is updated successfully.',
    STOREDELETED: 'Store is deleted successfully.',
    BOOKINGDELETED: 'Booking is deleted successfully.',
    LOCALURL: 'http://13.232.208.65:9000'
}

module.exports = constant